force-app/main/default/objects/Quote/fields/Primary_Quote__c.field-meta.xml
<CustomField>
    <fullName>Primary_Quote__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Project_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_End_Date__c</fullName>
    <label>Project End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Project_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Project_Start_Date__c</fullName>
    <label>Project Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Quoted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Quoted_Amount__c</fullName>
    <label>Quoted Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ReplacePrimaryQuoteTest.cls
@isTest
public class ReplacePrimaryQuoteTest {
    @isTest static void PrimaryQuoteTest() {
        Account accMRE = new Account();
        accMRE.Name = 'Red Ribbon Army';
        insert accMRE;
        
        Opportunity oppMRE = new Opportunity();
        oppMRE.Name = 'Replace Primary Quote Test';
        oppMRE.AccountId = accMRE.Id;
        oppMRE.RecordTypeId = Schema.SObjectType.opportunity.getRecordTypeInfosByName().get('Staffing').getRecordTypeId();
        oppMRE.StageName = 'Awareness';
        oppMRE.Competitive_Adj__c = 1.0;
        oppMRE.CloseDate = system.today();
        insert oppMRE;

        Quote existingQuote = new Quote();
        existingQuote.OpportunityId = oppMRE.Id;
        existingQuote.Status = 'Under Review';
        existingQuote.Project_Start_Date__c = system.today();
        existingQuote.Project_End_Date__c = system.today();
        existingQuote.Quoted_Amount__c = 200;
        existingQuote.Cost__c = 100;
        existingQuote.Primary_Quote__c = true;
        insert existingQuote;

        Quote newQuote = new Quote();
        newQuote.OpportunityId = oppMRE.Id;
        newQuote.Status = 'Under Review';
        newQuote.Project_Start_Date__c = system.today();
        newQuote.Project_End_Date__c = system.today();
        newQuote.Quoted_Amount__c = 200;
        newQuote.Cost__c = 100;
        insert newQuote;

        String quoteID = String.valueOf(newQuote.Id);

        ReplacePrimaryQuote.createQuoteFlowInput flowInput = new ReplacePrimaryQuote.createQuoteFlowInput();
        flowInput.quoteID = newQuote.Id;

        ReplacePrimaryQuote.ReplacePrimaryQuote(new List<ReplacePrimaryQuote.createQuoteFlowInput>{flowInput});

    }
}